import assert from "node:assert/strict";
import test from "node:test";
import { freelancerCashflowPlanner } from "../content/products/freelancer-cashflow-planner";
import { createPublicCatalog, validateCatalog } from "../lib/catalog/publication";
import { containsSecret, isWorkbookLike } from "../scripts/validate-publication";
import { calculate, coerceInput, defaults, validateManifest } from "../lib/showcase/core";
import { monthlySavingsShowcase } from "../content/showcases/monthly-savings";
import { freelancerCashflowShowcase } from "../content/showcases/freelancer-cashflow";
import { readFileSync } from "node:fs";

const valid = () => ({ ...freelancerCashflowPlanner, benefits: [...freelancerCashflowPlanner.benefits], compatibility: [...freelancerCashflowPlanner.compatibility] });
test("valid synthetic catalog passes", () => assert.doesNotThrow(() => validateCatalog([valid()])));
test("duplicate IDs and slugs fail", () => { assert.throws(() => validateCatalog([valid(), valid()])); assert.throws(() => validateCatalog([valid(), { ...valid(), productId: "prd_02A" }])); });
test("invalid prices fail", () => { assert.throws(() => validateCatalog([{ ...valid(), displayPrice: "free" }])); assert.throws(() => validateCatalog([{ ...valid(), displayPrice: "฿0" }])); });
test("synthetic sale-enabled products fail", () => assert.throws(() => validateCatalog([{ ...valid(), saleEnabled: true, saleAvailability: "available" }])));
test("public projection excludes internal fields", () => { const product = createPublicCatalog([valid()])[0]; assert.equal("internalSource" in product, false); assert.equal("saleEnabled" in product, false); });
test("workbook guard detects extensions and renamed synthetic ZIP signature", () => { assert.equal(isWorkbookLike("asset.xlsx", Buffer.from("text")), true); assert.equal(isWorkbookLike("fixture.bin", Buffer.from("PK fake [Content_Types].xml xl/workbook.xml")), true); assert.equal(isWorkbookLike("notes.zip", Buffer.from("PK harmless archive")), false); });
test("secret guard rejects credentials but allows normal content", () => { const databaseUri = "post" + "gresql://demo:" + "not-a-secret" + "@localhost:5432/commerce"; assert.equal(containsSecret("STRIPE" + "_SECRET_KEY=" + "sk_test_" + "123"), true); assert.equal(containsSecret(databaseUri), true); assert.equal(containsSecret("Synthetic fixture documentation"), false); assert.equal(containsSecret("COMMERCE_DATABASE_URL="), false); });
test("showcase validates, calculates, constrains inputs, and resets", () => { assert.doesNotThrow(() => validateManifest(monthlySavingsShowcase)); assert.equal(calculate(monthlySavingsShowcase, { monthlyIncome: 50000, monthlyExpense: 30000 }).outputs.remaining, 20000); assert.equal(coerceInput(monthlySavingsShowcase.inputs[0], Infinity), null); assert.deepEqual(defaults(monthlySavingsShowcase), { monthlyIncome: 50000, monthlyExpense: 30000 }); });
test("showcase rejects unknown calculators, blocks, and references", () => { assert.throws(() => validateManifest({ ...monthlySavingsShowcase, calculatorId: "unknown" })); assert.throws(() => validateManifest({ ...monthlySavingsShowcase, views: [{ ...monthlySavingsShowcase.views[0], blocks: [{ id: "bad", type: "input", inputId: "unknown" }] }] })); });
test("showcase keeps public text escaped and chart data table-backed", () => { assert.doesNotThrow(() => validateManifest({ ...monthlySavingsShowcase, disclosure: "<script>not executed</script>" })); assert.equal(readFileSync("components/showcase/Showcase.tsx", "utf8").includes("dangerouslySetInnerHTML"), false); const result = calculate(monthlySavingsShowcase, defaults(monthlySavingsShowcase)); assert.deepEqual(result.tables.monthly, result.series.monthly); });
test("freelancer scenario is deterministic, bounded, and table-parity safe", () => { const base = defaults(freelancerCashflowShowcase); const result = calculate(freelancerCashflowShowcase, base); assert.equal(result.outputs.remaining, 20000); assert.equal(result.outputs.commitments, 30000); assert.deepEqual(result.tables.monthly, result.series.monthly); assert.equal(coerceInput(freelancerCashflowShowcase.inputs[0], -1), null); assert.deepEqual(freelancerCashflowShowcase.scenarios?.[1].values.monthlyIncome, 40000); });
