export type Input = { id: string; label: string; kind: "number"; default: number; min: number; max: number; step: number; unit: string };
export type Block = { id: string; type: "text"; text: string } | { id: string; type: "input"; inputId: string } | { id: string; type: "output"; outputId: string; label: string } | { id: string; type: "table"; tableId: string; columns: readonly string[] } | { id: string; type: "chart"; seriesId: string; tableId: string; label: string };
export type Manifest = { schemaVersion: 1; id: string; productId: string; title: string; disclosure: string; provenance: string; calculatorId: string; inputs: readonly Input[]; views: readonly { id: string; title: string; blocks: readonly Block[] }[] };
export type Calculation = { outputs: Record<string, number>; tables: Record<string, readonly { label: string; value: number }[]>; series: Record<string, readonly { label: string; value: number }[]> };
const calculators: Record<string, (values: Record<string, number>) => Calculation> = { "monthly-savings": (v) => { const rows = [{ label: "Income", value: v.monthlyIncome }, { label: "Expense", value: v.monthlyExpense }]; return { outputs: { remaining: v.monthlyIncome - v.monthlyExpense }, tables: { monthly: rows }, series: { monthly: rows } }; } };
export function validateManifest(manifest: Manifest) { const ids = new Set<string>(); if (manifest.schemaVersion !== 1 || !manifest.id || !manifest.productId || !calculators[manifest.calculatorId]) throw new Error("Invalid showcase metadata or calculator"); if (manifest.inputs.length > 20 || manifest.views.length > 5) throw new Error("Showcase exceeds contract bounds"); for (const input of manifest.inputs) { if (!input.id || ids.has(input.id) || !Number.isFinite(input.default) || input.default < input.min || input.default > input.max || input.min > input.max) throw new Error("Invalid showcase input"); ids.add(input.id); } const viewIds = new Set<string>(); for (const view of manifest.views) { if (!view.id || viewIds.has(view.id)) throw new Error("Invalid showcase view"); viewIds.add(view.id); for (const block of view.blocks) { if (!block.id || !["text", "input", "output", "table", "chart"].includes(block.type)) throw new Error("Unsupported showcase block"); if (block.type === "input" && !ids.has(block.inputId)) throw new Error("Unknown input reference"); if (block.type === "chart" && block.tableId !== "monthly") throw new Error("Unknown chart table reference"); } } }
export function defaults(manifest: Manifest) { return Object.fromEntries(manifest.inputs.map((input) => [input.id, input.default])); }
export function coerceInput(input: Input, value: number) { return Number.isFinite(value) && value >= input.min && value <= input.max ? value : null; }
export function calculate(manifest: Manifest, values: Record<string, number>) { return calculators[manifest.calculatorId](values); }
